### ISSUE TITLE
Error on Mathew Johnson's java libraries version

### ISSUE THREAD

**Issue by david-gomez-fernandez** [Agile-IoT/agile-dbus-java-interface#1]
It seems that the version set in the `scripts/install-dependencies.sh` file points to a deprecated (and deleted) [file](http://www.matthew.ath.cx/projects/java/libmatthew-java-0.8.tar.gz). As a consequence, the compilation from the source code crashes. 

> --2018-05-22 07:18:14--  http://www.matthew.ath.cx/projects/java/libmatthew-java-0.8.tar.gz
Resolving www.matthew.ath.cx (www.matthew.ath.cx)... 46.235.228.127, 2a00:1098:86:11::1
Connecting to www.matthew.ath.cx (www.matthew.ath.cx)|46.235.228.127|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.matthew.ath.cx/errors/404 [following]
--2018-05-22 07:18:14--  http://www.matthew.ath.cx/errors/404
Reusing existing connection to www.matthew.ath.cx:80.
HTTP request sent, awaiting response... 200 OK
Length: 8683 (8.5K) [text/html]
Saving to: ‘libmatthew-java-0.8.tar.gz’
     0K ........                                              100% 22.0M=0s
2018-05-22 07:18:14 (22.0 MB/s) - ‘libmatthew-java-0.8.tar.gz’ saved [8683/8683]
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat ‘libmatthew-java-0.8’: No such file or directory
./scripts/install-dependencies.sh: 26: cd: can't cd to /usr/src/app/deps/build/libmatthew-java-0.8

To fix this, the solution is immediate: in the aforementioned file, line 16, `LMLIB=0.8`. Nonetheless, it is worth mentioning that, though the compilation does not fail, it triggers a number of warnings that may lead to problems in the future

**Comment by cskiraly** [comment]
Thanks David, I've fixed this in https://github.com/Agile-IoT/agile-dbus-java-interface/commit/a0ad36a74358a8094e6f72dc309e2294ca870b9f
