### ISSUE TITLE
Wrong version of libmatthew-java

### ISSUE THREAD

**Issue by gabiSRC** [Agile-IoT/agile-dbus-java-interface#3]
Hello,
I notice that there is LMLIB=0.8 but this does not exist anymore and should be replaced by LMLIB=0.8.1 (check it on http://www.matthew.ath.cx/projects/java/)

**Comment by cskiraly** [comment]
Thanks, we have updated it in https://github.com/Agile-IoT/agile-dbus-java-interface/commit/a0ad36a74358a8094e6f72dc309e2294ca870b9f
